[project]
name = "habit-tracker"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django (==4.2.0)",
    "psycopg2-binary (>=2.9.12,<3.0.0)",
    "djangorestframework (==3.14.0)",
    "djangorestframework-simplejwt (==5.3.1)",
    "django-cors-headers (==3.13.0)",
    "drf-spectacular (==0.24.2)",
    "celery (==5.2.7)",
    "redis (==4.5.1)",
    "python-dotenv (==1.0.0)",
    "setuptools (>=83.0.0,<84.0.0)",
    "wheel (>=0.47.0,<0.48.0)",
    "drf-jwt (==1.19.2)",
    "drf-yasg (>=1.21.15,<2.0.0)",
    "telegram (>=0.0.1,<0.0.2)",
    "python-telegram-bot (>=22.8,<23.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
lint = [
    "black (>=26.5.1,<27.0.0)",
    "isort (>=8.0.1,<9.0.0)"
]
